#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@turboacc[-1]
	add ucitrack turboacc
	set ucitrack.@turboacc[-1].init=turboacc
	commit ucitrack
EOF

[ -n "$(lsmod | grep mtkhnat)" ] && \
	uci set turboacc.config.sw_flow='0' && \
	uci set turboacc.config.hw_flow='0'

# MediaTek HNAT available (21.02 based MTK targets): default to mtkhnat offloading
kernel_ver="$(uname -r)"
[ -e "/lib/modules/$kernel_ver/mtkhnat.ko" ] && \
	uci set turboacc.config.hnat_flow='1' && \
	uci set turboacc.config.sw_flow='0' && \
	uci set turboacc.config.hw_flow='0' && \
	uci set turboacc.config.sfe_flow='0'

uci commit turboacc

exit 0
